language: node_js
node_js: 12

os: linux
dist: xenial

branches:
  only:
  - master
  - develop

stages:
  - name: build
  - name: test

jobs:
  include:
  - name: build
    stage: Build
    install: npm i
    script: npm run build
  - name: Unit Tests
    stage: test
    script: npm run test